apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mlg---test-of-wizard
  title: mlg - test of wizard
  description: test test
  annotations:
    github.com/project-slug: bcgov/mlg-test-repo-1
    backstage.io/techdocs-ref: dir:.
    bcgovpubcode.gov.bc.ca/ministry: CITZ
    bcgovpubcode.gov.bc.ca/product_name: test
    bcgovpubcode.gov.bc.ca/product_description: test test
    bcgovpubcode.gov.bc.ca/product_acronym: test
    bcgovpubcode.gov.bc.ca/product_owner: Monica
    bcgovpubcode.gov.bc.ca/hosting_platform: Not-Applicable
    backstage.io/source-template: template:default/docs-template
spec:
  type: documentation
  lifecycle: experimental
  owner: group:default/developer-experience-developers
